import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1763206381666 implements MigrationInterface {
    name = 'InitialSchema1763206381666'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."categories_type_enum" AS ENUM('income', 'expense', 'both')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."categories_type_enum" NOT NULL, "icon" character varying, "color" character varying, "isDefault" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "isArchived" boolean NOT NULL DEFAULT false, "description" text, "usageCount" integer NOT NULL DEFAULT '0', "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "parentId" uuid, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "color" character varying, "isDefault" boolean NOT NULL DEFAULT false, "description" text, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transactionId" uuid NOT NULL, "categoryId" uuid, "description" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "sortOrder" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_49de91e16c52b342bfc02dac000" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7a6a724f3c1992fb26f80d789" ON "transaction_line_items" ("transactionId") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('income', 'expense', 'transfer', 'lend', 'borrow', 'group')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_source_enum" AS ENUM('manual', 'email', 'file_import', 'api', 'chat')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_sourcetype_enum" AS ENUM('manual', 'investment', 'shared_expense', 'recurring')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "type" "public"."transactions_type_enum" NOT NULL, "date" date NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "source" "public"."transactions_source_enum" NOT NULL DEFAULT 'manual', "notes" text, "location" character varying, "attachments" text, "referenceNumber" character varying, "isRecurring" boolean NOT NULL DEFAULT false, "recurringFrequency" character varying, "transferToAccountId" character varying, "groupTransactionId" character varying, "lendBorrowId" character varying, "metadata" jsonb, "mergedIntoId" character varying, "isMerged" boolean NOT NULL DEFAULT false, "mergedAt" TIMESTAMP, "duplicateExclusions" text, "sourceType" "public"."transactions_sourcetype_enum" NOT NULL DEFAULT 'manual', "sourceId" character varying, "userId" uuid NOT NULL, "accountId" uuid NOT NULL, "categoryId" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "isVerified" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, "updatedBy" character varying, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e43dcec1b431001441c3983cd" ON "transactions" ("sourceType", "sourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da2770eb9a35f7ad1fdaf64601" ON "transactions" ("accountId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3dae3ed25e0d76f419fcb89ead" ON "transactions" ("userId", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_31c0fafe7c59f688d0e7e7e322" ON "transactions" ("userId", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."accounts_type_enum" AS ENUM('bank', 'wallet', 'cash', 'card', 'investment', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_reconciliationstatus_enum" AS ENUM('none', 'in_progress', 'reconciled')`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."accounts_type_enum" NOT NULL, "balance" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "accountNumber" character varying, "bankName" character varying, "icon" character varying, "color" character varying, "isActive" boolean NOT NULL DEFAULT true, "includeInTotal" boolean NOT NULL DEFAULT true, "description" text, "reconciliationStatus" "public"."accounts_reconciliationstatus_enum" NOT NULL DEFAULT 'none', "lastReconciledAt" TIMESTAMP, "lastReconciledBalance" numeric(15,2), "statementPassword" text, "isTemporary" boolean NOT NULL DEFAULT false, "tempAccountSource" text, "linkedToAccountId" uuid, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."budgets_period_enum" AS ENUM('weekly', 'monthly', 'quarterly', 'yearly', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."budgets_type_enum" AS ENUM('category', 'tag', 'overall', 'group')`);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "period" "public"."budgets_period_enum" NOT NULL, "type" "public"."budgets_type_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "categoryId" character varying, "tagId" character varying, "groupId" character varying, "isActive" boolean NOT NULL DEFAULT true, "alertEnabled" boolean NOT NULL DEFAULT false, "alertThreshold" integer NOT NULL DEFAULT '80', "aiGenerated" boolean NOT NULL DEFAULT false, "notes" text, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_transactions_splittype_enum" AS ENUM('equal', 'custom', 'percentage', 'shares')`);
        await queryRunner.query(`CREATE TABLE "group_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "date" date NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "paidBy" character varying NOT NULL, "splitType" "public"."group_transactions_splittype_enum" NOT NULL DEFAULT 'equal', "splits" jsonb NOT NULL, "notes" text, "attachments" text, "categoryId" character varying, "groupId" uuid NOT NULL, "isSettlement" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying NOT NULL, "updatedBy" character varying, CONSTRAINT "PK_11870298f3bf7ba26a70618ca8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "icon" character varying, "color" character varying, "currency" character varying NOT NULL DEFAULT 'USD', "isActive" boolean NOT NULL DEFAULT true, "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_members_role_enum" AS ENUM('admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "groupId" uuid NOT NULL, "role" "public"."group_members_role_enum" NOT NULL DEFAULT 'member', "balance" numeric(15,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86446139b2c96bfd0f3b8638852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."investments_type_enum" AS ENUM('stocks', 'mutual_funds', 'bonds', 'crypto', 'fixed_deposit', 'real_estate', 'gold', 'other')`);
        await queryRunner.query(`CREATE TABLE "investments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."investments_type_enum" NOT NULL, "investedAmount" numeric(15,2) NOT NULL, "currentValue" numeric(15,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "investmentDate" date NOT NULL, "maturityDate" date, "broker" character varying, "accountNumber" character varying, "notes" text, "isActive" boolean NOT NULL DEFAULT true, "additionalData" jsonb, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a1263853f1a4fb8b849c1c9aff4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lend_borrow_type_enum" AS ENUM('lend', 'borrow')`);
        await queryRunner.query(`CREATE TYPE "public"."lend_borrow_status_enum" AS ENUM('pending', 'partial', 'settled')`);
        await queryRunner.query(`CREATE TABLE "lend_borrow" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."lend_borrow_type_enum" NOT NULL, "personName" character varying NOT NULL, "personEmail" character varying, "personPhone" character varying, "amount" numeric(15,2) NOT NULL, "amountPaid" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "date" date NOT NULL, "dueDate" date, "status" "public"."lend_borrow_status_enum" NOT NULL DEFAULT 'pending', "description" text, "notes" text, "attachments" text, "transactionId" character varying, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a15f891005e5287b867b866c235" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('budget_alert', 'group_settlement', 'due_repayment', 'ai_insight', 'import_complete', 'reminder', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('unread', 'read', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'unread', "data" jsonb, "link" character varying, "userId" uuid NOT NULL, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reminders_type_enum" AS ENUM('bill', 'repayment', 'goal', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."reminders_frequency_enum" AS ENUM('once', 'daily', 'weekly', 'monthly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."reminders_status_enum" AS ENUM('active', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "reminders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "type" "public"."reminders_type_enum" NOT NULL, "dueDate" date NOT NULL, "frequency" "public"."reminders_frequency_enum" NOT NULL DEFAULT 'once', "amount" numeric(15,2), "currency" character varying NOT NULL DEFAULT 'USD', "status" "public"."reminders_status_enum" NOT NULL DEFAULT 'active', "notificationEnabled" boolean NOT NULL DEFAULT true, "notifyDaysBefore" integer NOT NULL DEFAULT '1', "categoryId" character varying, "accountId" character varying, "lendBorrowId" character varying, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_38715fec7f634b72c6cf7ea4893" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_connections_provider_enum" AS ENUM('gmail', 'outlook', 'yahoo', 'imap', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."email_connections_status_enum" AS ENUM('connected', 'disconnected', 'error', 'syncing', 'expired')`);
        await queryRunner.query(`CREATE TABLE "email_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "provider" "public"."email_connections_provider_enum" NOT NULL, "encryptedPassword" text, "accessToken" text, "refreshToken" text, "tokenExpiresAt" TIMESTAMP, "imapHost" character varying, "imapPort" integer, "useTLS" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "status" "public"."email_connections_status_enum" NOT NULL DEFAULT 'disconnected', "errorMessage" character varying(500), "lastSyncAt" TIMESTAMP, "lastSyncHistoryId" character varying(255), "transactionsExtracted" integer NOT NULL DEFAULT '0', "ordersExtracted" integer NOT NULL DEFAULT '0', "syncError" text, "autoSync" boolean NOT NULL DEFAULT true, "preferences" jsonb, "syncStats" jsonb, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7190425eab77d1c9a75a0e36573" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "deviceInfo" jsonb NOT NULL, "ipAddress" character varying NOT NULL, "location" character varying, "lastActive" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "refreshToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57de40bc620f456c7311aa3a1e" ON "sessions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39f8752ebc359f7595484507ca" ON "sessions" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_07bd9c0d345c7e1110981e3431" ON "sessions" ("userId", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_tier_enum" AS ENUM('free', 'basic', 'premium', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'canceled', 'expired', 'past_due', 'trialing')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tier" "public"."subscriptions_tier_enum" NOT NULL DEFAULT 'free', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "billingCycle" "public"."subscriptions_billingcycle_enum", "price" numeric(10,2), "stripeCustomerId" character varying, "stripeSubscriptionId" character varying, "stripePriceId" character varying, "currentPeriodStart" TIMESTAMP, "currentPeriodEnd" TIMESTAMP, "trialStart" TIMESTAMP, "trialEnd" TIMESTAMP, "canceledAt" TIMESTAMP, "cancelAtPeriodEnd" TIMESTAMP, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_subscriptiontier_enum" AS ENUM('free', 'basic', 'premium', 'enterprise')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "photo" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "subscriptionTier" "public"."users_subscriptiontier_enum" NOT NULL DEFAULT 'free', "subscriptionExpiry" TIMESTAMP, "language" character varying NOT NULL DEFAULT 'en', "region" character varying NOT NULL DEFAULT 'US', "currency" character varying NOT NULL DEFAULT 'USD', "isActive" boolean NOT NULL DEFAULT true, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "passwordResetToken" character varying, "passwordResetExpiry" TIMESTAMP, "twoFactorSecret" character varying, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "twoFactorBackupCodes" text, "refreshToken" character varying, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_dashboard_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "widgets" jsonb NOT NULL DEFAULT '[]', "gridColumns" integer NOT NULL DEFAULT '3', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_965f9dd94d2a87efac9027f22c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usage_tracking" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "period" character varying NOT NULL, "transactionsCount" integer NOT NULL DEFAULT '0', "accountsCount" integer NOT NULL DEFAULT '0', "budgetsCount" integer NOT NULL DEFAULT '0', "groupsCount" integer NOT NULL DEFAULT '0', "investmentsCount" integer NOT NULL DEFAULT '0', "reportsCount" integer NOT NULL DEFAULT '0', "apiCallsCount" integer NOT NULL DEFAULT '0', "exportsCount" integer NOT NULL DEFAULT '0', "importsCount" integer NOT NULL DEFAULT '0', "storageUsed" bigint NOT NULL DEFAULT '0', "aiAssistantCalls" integer NOT NULL DEFAULT '0', "advancedAnalyticsViews" integer NOT NULL DEFAULT '0', "insightsGenerated" integer NOT NULL DEFAULT '0', "lastUpdated" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2879a43395bb513204f88769aa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78c3bbc3ce218c9b0c62b81d51" ON "usage_tracking" ("userId", "period") `);
        await queryRunner.query(`CREATE TYPE "public"."shared_expense_participants_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "shared_expense_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupId" uuid NOT NULL, "userId" uuid, "participantName" character varying, "participantEmail" character varying, "role" "public"."shared_expense_participants_role_enum" NOT NULL DEFAULT 'member', "balance" numeric(15,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de6f579f837d8cd7d40fcfe751a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c452908fa3271266e1a651389c" ON "shared_expense_participants" ("groupId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."shared_expense_groups_type_enum" AS ENUM('personal_debt', 'group_expense', 'trip', 'household')`);
        await queryRunner.query(`CREATE TYPE "public"."shared_expense_groups_debtdirection_enum" AS ENUM('lend', 'borrow')`);
        await queryRunner.query(`CREATE TABLE "shared_expense_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type" "public"."shared_expense_groups_type_enum" NOT NULL, "isOneToOne" boolean NOT NULL DEFAULT false, "participantCount" integer NOT NULL DEFAULT '2', "otherPersonName" character varying, "otherPersonEmail" character varying, "otherPersonPhone" character varying, "debtDirection" "public"."shared_expense_groups_debtdirection_enum", "icon" character varying, "color" character varying, "currency" character varying NOT NULL DEFAULT 'USD', "isActive" boolean NOT NULL DEFAULT true, "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e2da354f25c2d830a8fa277926" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_07cfc4547c2ae61a7b18e0f40a" ON "shared_expense_groups" ("isOneToOne", "isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfe742520fdd67ee752446e407" ON "shared_expense_groups" ("createdBy", "isOneToOne") `);
        await queryRunner.query(`CREATE TYPE "public"."shared_expense_transactions_splittype_enum" AS ENUM('equal', 'custom', 'percentage', 'shares', 'full')`);
        await queryRunner.query(`CREATE TABLE "shared_expense_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "date" date NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "paidBy" character varying NOT NULL, "splitType" "public"."shared_expense_transactions_splittype_enum" NOT NULL DEFAULT 'equal', "splits" jsonb NOT NULL, "notes" text, "attachments" text, "categoryId" uuid, "groupId" uuid NOT NULL, "isSettlement" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP, "createdBy" character varying NOT NULL, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_73b644492ac93557de38b046498" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa8e48aa9c9e63bc7e4a11017a" ON "shared_expense_transactions" ("groupId", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."generated_reports_format_enum" AS ENUM('pdf', 'excel', 'csv', 'json')`);
        await queryRunner.query(`CREATE TYPE "public"."generated_reports_status_enum" AS ENUM('pending', 'generating', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "generated_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportId" uuid NOT NULL, "format" "public"."generated_reports_format_enum" NOT NULL, "status" "public"."generated_reports_status_enum" NOT NULL DEFAULT 'pending', "fileUrl" character varying, "fileName" character varying, "fileSize" bigint, "metadata" jsonb, "error" text, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "generatedBy" character varying, CONSTRAINT "PK_3875618b27e8f2d438168399374" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38d02b1ddad80789c3721da73e" ON "generated_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4debd78ff0a7ebd62fc8913201" ON "generated_reports" ("reportId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('custom', 'monthly_summary', 'tax_report', 'year_over_year', 'month_over_month', 'quarter_over_quarter', 'budget_vs_actual', 'category_spending', 'investment_performance', 'group_expense_settlement', 'cash_flow', 'net_worth', 'profit_loss')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type" "public"."reports_type_enum" NOT NULL, "config" jsonb NOT NULL, "schedule" jsonb, "isFavorite" boolean NOT NULL DEFAULT false, "isShared" boolean NOT NULL DEFAULT false, "sharedWithGroupIds" text, "runCount" integer NOT NULL DEFAULT '0', "lastRunAt" TIMESTAMP, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_145191ba0ef71c378ae0164b94" ON "reports" ("userId", "isFavorite") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7e731077832d2b53fa160a3e2" ON "reports" ("userId", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."recurring_group_transactions_splittype_enum" AS ENUM('equal', 'custom', 'percentage', 'shares')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_group_transactions_frequency_enum" AS ENUM('daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."recurring_group_transactions_status_enum" AS ENUM('active', 'paused', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "recurring_group_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying NOT NULL, "amount" numeric(15,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "paidBy" character varying NOT NULL, "splitType" "public"."recurring_group_transactions_splittype_enum" NOT NULL DEFAULT 'equal', "splits" jsonb NOT NULL, "notes" text, "categoryId" character varying, "groupId" uuid NOT NULL, "frequency" "public"."recurring_group_transactions_frequency_enum" NOT NULL, "startDate" date NOT NULL, "endDate" date, "maxOccurrences" integer, "occurrencesCreated" integer NOT NULL DEFAULT '0', "lastProcessedDate" date, "nextProcessDate" date, "status" "public"."recurring_group_transactions_status_enum" NOT NULL DEFAULT 'active', "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying NOT NULL, "updatedBy" character varying, CONSTRAINT "PK_13c9b22a5a7fd52fa5758246963" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reconciliation_transactions_matchconfidence_enum" AS ENUM('exact', 'high', 'medium', 'low', 'manual')`);
        await queryRunner.query(`CREATE TABLE "reconciliation_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reconciliationId" uuid NOT NULL, "transactionId" uuid, "matched" boolean NOT NULL DEFAULT false, "matchConfidence" "public"."reconciliation_transactions_matchconfidence_enum", "confidenceScore" numeric(5,2), "statementAmount" numeric(15,2) NOT NULL, "statementDate" date NOT NULL, "statementDescription" character varying NOT NULL, "statementReferenceNumber" character varying, "notes" text, "isManualMatch" boolean NOT NULL DEFAULT false, "matchingDetails" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c21db14c7dde02067e833eb79ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6bc078fe62cc2ef67391e4922" ON "reconciliation_transactions" ("reconciliationId", "matched") `);
        await queryRunner.query(`CREATE TYPE "public"."reconciliations_status_enum" AS ENUM('in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "reconciliations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountId" uuid NOT NULL, "userId" uuid NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "statementBalance" numeric(15,2) NOT NULL, "reconciledBalance" numeric(15,2), "difference" numeric(15,2) NOT NULL DEFAULT '0', "status" "public"."reconciliations_status_enum" NOT NULL DEFAULT 'in_progress', "completedAt" TIMESTAMP, "notes" text, "matchedCount" integer NOT NULL DEFAULT '0', "unmatchedCount" integer NOT NULL DEFAULT '0', "statementTransactionCount" integer NOT NULL DEFAULT '0', "summary" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_110f3839ca29e2fd8ff4aaec7b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a5214a8a174bf9312ae5935b6f" ON "reconciliations" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a875c91116976c6180e5ce593e" ON "reconciliations" ("accountId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."job_logs_level_enum" AS ENUM('debug', 'info', 'warning', 'error')`);
        await queryRunner.query(`CREATE TABLE "job_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobId" uuid NOT NULL, "level" "public"."job_logs_level_enum" NOT NULL, "message" text NOT NULL, "context" jsonb, "stackTrace" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58193ed7a13b6627e99dc1c0985" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eeac166e095d6b7ecf8d154397" ON "job_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd7b8fde937e0dfdad9c689aa4" ON "job_logs" ("jobId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."jobs_type_enum" AS ENUM('email_sync', 'transaction_import', 'report_generation', 'insights_generation', 'budget_refresh', 'notification_digest', 'cache_cleanup', 'backup_verification', 'account_reconciliation', 'data_export')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum" AS ENUM('waiting', 'active', 'completed', 'failed', 'delayed', 'paused', 'stuck')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_priority_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bullJobId" character varying NOT NULL, "queueName" character varying NOT NULL, "type" "public"."jobs_type_enum" NOT NULL, "status" "public"."jobs_status_enum" NOT NULL, "priority" "public"."jobs_priority_enum" NOT NULL DEFAULT '2', "data" jsonb NOT NULL, "progress" jsonb, "result" jsonb, "error" text, "stackTrace" text, "attempts" integer NOT NULL DEFAULT '0', "maxAttempts" integer NOT NULL DEFAULT '3', "userId" character varying, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "failedAt" TIMESTAMP, "processedBy" character varying, "duration" integer NOT NULL DEFAULT '0', "timeout" integer, "isDuplicate" boolean NOT NULL DEFAULT false, "deduplicationKey" character varying, "rateLimitKey" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c98461a2c1599bfcf60985678d9" UNIQUE ("bullJobId"), CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c98461a2c1599bfcf60985678d" ON "jobs" ("bullJobId") `);
        await queryRunner.query(`CREATE INDEX "IDX_79ae682707059d5f7655db4212" ON "jobs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6975aa7cefaae1209a4784e88b" ON "jobs" ("queueName", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc6f555dc06b89ce79ca00685b" ON "jobs" ("type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_af924c25aab35b33928211bb1f" ON "jobs" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'open', 'paid', 'void', 'uncollectible')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_tier_enum" AS ENUM('free', 'basic', 'premium', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_billingcycle_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "invoiceNumber" character varying NOT NULL, "stripeInvoiceId" character varying, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "tier" "public"."invoices_tier_enum" NOT NULL, "billingCycle" "public"."invoices_billingcycle_enum" NOT NULL, "subtotal" numeric(10,2) NOT NULL, "tax" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "currency" character varying NOT NULL, "periodStart" TIMESTAMP NOT NULL, "periodEnd" TIMESTAMP NOT NULL, "dueDate" TIMESTAMP, "paidAt" TIMESTAMP, "paymentMethod" character varying, "receiptUrl" character varying, "pdfUrl" character varying, "lineItems" json, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf8e0f9dd4558ef209ec111782d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3ed03c025d92c4c34131e577f" ON "invoices" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."import_logs_filetype_enum" AS ENUM('csv', 'excel', 'pdf', 'email', 'api')`);
        await queryRunner.query(`CREATE TYPE "public"."import_logs_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'partially_completed')`);
        await queryRunner.query(`CREATE TABLE "import_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying NOT NULL, "fileType" "public"."import_logs_filetype_enum" NOT NULL, "fileSize" integer, "filePath" character varying, "status" "public"."import_logs_status_enum" NOT NULL DEFAULT 'pending', "totalRecords" integer NOT NULL DEFAULT '0', "successfulRecords" integer NOT NULL DEFAULT '0', "failedRecords" integer NOT NULL DEFAULT '0', "duplicateRecords" integer NOT NULL DEFAULT '0', "errors" jsonb, "metadata" jsonb, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_605638f3d14c87ce06601313f0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "groupId" uuid NOT NULL, "userId" uuid NOT NULL, "transactionId" character varying, "parentCommentId" uuid, "isEdited" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2af959e442cb43c7db847d0e654" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_budgets_period_enum" AS ENUM('daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'custom')`);
        await queryRunner.query(`CREATE TABLE "group_budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "amount" numeric(15,2) NOT NULL, "spent" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "period" "public"."group_budgets_period_enum" NOT NULL DEFAULT 'monthly', "startDate" date NOT NULL, "endDate" date, "categoryId" character varying, "groupId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "notifyWhenExceeded" boolean NOT NULL DEFAULT false, "warningThreshold" integer NOT NULL DEFAULT '80', "lastResetDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying NOT NULL, "updatedBy" character varying, CONSTRAINT "PK_9f97b6725c8d78df1c2c7fcae33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "deleted_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "originalUserId" character varying NOT NULL, "reason" character varying, "metadata" text, "deletedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e912c54f66fe8d22c12de2ad253" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'login', 'logout', 'export', 'import')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" character varying NOT NULL, "entityId" character varying, "oldValues" jsonb, "newValues" jsonb, "ipAddress" character varying, "userAgent" character varying, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e589da8f9e9326ee0d01a028" ON "audit_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_categorization_feedback_feedbacktype_enum" AS ENUM('accept', 'reject', 'correct')`);
        await queryRunner.query(`CREATE TABLE "ai_categorization_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "transactionId" uuid NOT NULL, "transactionDescription" text NOT NULL, "suggestedCategoryId" uuid, "correctCategoryId" uuid, "feedbackType" "public"."ai_categorization_feedback_feedbacktype_enum" NOT NULL, "originalConfidence" numeric(5,4), "alternativeSuggestions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f53184fb06ddc4a0f9d9caab1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."addons_type_enum" AS ENUM('storage', 'transactions', 'api_calls', 'users', 'reports', 'custom_feature')`);
        await queryRunner.query(`CREATE TYPE "public"."addons_status_enum" AS ENUM('active', 'expired', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "type" "public"."addons_type_enum" NOT NULL, "status" "public"."addons_status_enum" NOT NULL DEFAULT 'active', "price" numeric(10,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'USD', "isRecurring" boolean NOT NULL DEFAULT false, "quantity" integer, "unit" character varying, "stripeProductId" character varying, "stripePriceId" character varying, "validFrom" TIMESTAMP, "validUntil" TIMESTAMP, "purchasedAt" TIMESTAMP, "canceledAt" TIMESTAMP, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cd49fb3dc0558f02cb6fe6cc138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6364785c61032ef525bf97c2dc" ON "addons" ("userId", "status") `);
        await queryRunner.query(`CREATE TABLE "transaction_tags" ("transactionId" uuid NOT NULL, "tagId" uuid NOT NULL, CONSTRAINT "PK_172ada2fd5d5d973411a5157348" PRIMARY KEY ("transactionId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_23ed9c8ca2e4b5cf639c580e50" ON "transaction_tags" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccbbef396290acaece98cb129b" ON "transaction_tags" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "categories_closure" ("id_ancestor" uuid NOT NULL, "id_descendant" uuid NOT NULL, CONSTRAINT "PK_dc67f6a82852c15ec6e4243398d" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ea1e9c4eea91160dfdb4318778" ON "categories_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_51fff5114cc41723e8ca36cf22" ON "categories_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_13e8b2a21988bec6fdcbb1fa741" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_92e67dc508c705dd66c94615576" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_line_items" ADD CONSTRAINT "FK_a7a6a724f3c1992fb26f80d789d" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_line_items" ADD CONSTRAINT "FK_91408ba875d13b05f5e33ab30be" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_26d8aec71ae9efbe468043cd2b9" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_86e965e74f9cc66149cf6c90f64" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_27e688ddf1ff3893b43065899f9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_transactions" ADD CONSTRAINT "FK_52d3ec14942246a20ec089aabe2" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_fdef099303bcf0ffd9a4a7b18f5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "investments" ADD CONSTRAINT "FK_1ee4fc01d07959ee6cf7926fe3c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lend_borrow" ADD CONSTRAINT "FK_15bc0e08b91d382c425bff2b4c6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminders" ADD CONSTRAINT "FK_f8e4bc520d9e692652afaf3308b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_connections" ADD CONSTRAINT "FK_7fd20b5b5314e110cf3485e6dfb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_dashboard_preferences" ADD CONSTRAINT "FK_de3bbecc57255aaa3a47d2d6029" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ADD CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_expense_participants" ADD CONSTRAINT "FK_e59e0fd593eb4573b4d139c32ea" FOREIGN KEY ("groupId") REFERENCES "shared_expense_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_expense_participants" ADD CONSTRAINT "FK_356748a64fccab022d426a99ffe" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_expense_transactions" ADD CONSTRAINT "FK_5f35ed5eab41cccf3f3914f43f6" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_expense_transactions" ADD CONSTRAINT "FK_37970e3ecd44f15e2c46dcb7c9e" FOREIGN KEY ("groupId") REFERENCES "shared_expense_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_reports" ADD CONSTRAINT "FK_155cad17f9ead409d635bf1d979" FOREIGN KEY ("reportId") REFERENCES "reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_group_transactions" ADD CONSTRAINT "FK_fbf2783c89afadf2261bbdb5254" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliation_transactions" ADD CONSTRAINT "FK_55e3d0d29651d7e34abf0d59caf" FOREIGN KEY ("reconciliationId") REFERENCES "reconciliations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliation_transactions" ADD CONSTRAINT "FK_e39489108160bed58ddcdec73c6" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD CONSTRAINT "FK_89f69f854c22241e85e23152924" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconciliations" ADD CONSTRAINT "FK_8d15ec28e9433be2c9c9ffbd13a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_logs" ADD CONSTRAINT "FK_35fcfcba9d292c0c1738b8edd97" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_logs" ADD CONSTRAINT "FK_9ab8584c123f87f734ced9aa5b6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_comments" ADD CONSTRAINT "FK_0385d76d1946d4034a363c4234d" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_comments" ADD CONSTRAINT "FK_1bdbdc1045f1ecc53c1eaa81a9d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_comments" ADD CONSTRAINT "FK_d3672fb89d18f9947692f3294d2" FOREIGN KEY ("parentCommentId") REFERENCES "group_comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_budgets" ADD CONSTRAINT "FK_1cdfb36ba1c5b230fc8bb85774f" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" ADD CONSTRAINT "FK_4176f82faa6aa203d476fc20ea3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" ADD CONSTRAINT "FK_c77550a7ee4a3b5780c65c302aa" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" ADD CONSTRAINT "FK_d851b6258dcab528695421752ea" FOREIGN KEY ("suggestedCategoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" ADD CONSTRAINT "FK_0926ce8de2bf6fb8c57e946e270" FOREIGN KEY ("correctCategoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addons" ADD CONSTRAINT "FK_a02a32eee245a4e6c23fce3126d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tags" ADD CONSTRAINT "FK_23ed9c8ca2e4b5cf639c580e50b" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transaction_tags" ADD CONSTRAINT "FK_ccbbef396290acaece98cb129b6" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories_closure" ADD CONSTRAINT "FK_ea1e9c4eea91160dfdb4318778d" FOREIGN KEY ("id_ancestor") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories_closure" ADD CONSTRAINT "FK_51fff5114cc41723e8ca36cf227" FOREIGN KEY ("id_descendant") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "categories_closure" DROP CONSTRAINT "FK_51fff5114cc41723e8ca36cf227"`);
        await queryRunner.query(`ALTER TABLE "categories_closure" DROP CONSTRAINT "FK_ea1e9c4eea91160dfdb4318778d"`);
        await queryRunner.query(`ALTER TABLE "transaction_tags" DROP CONSTRAINT "FK_ccbbef396290acaece98cb129b6"`);
        await queryRunner.query(`ALTER TABLE "transaction_tags" DROP CONSTRAINT "FK_23ed9c8ca2e4b5cf639c580e50b"`);
        await queryRunner.query(`ALTER TABLE "addons" DROP CONSTRAINT "FK_a02a32eee245a4e6c23fce3126d"`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" DROP CONSTRAINT "FK_0926ce8de2bf6fb8c57e946e270"`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" DROP CONSTRAINT "FK_d851b6258dcab528695421752ea"`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" DROP CONSTRAINT "FK_c77550a7ee4a3b5780c65c302aa"`);
        await queryRunner.query(`ALTER TABLE "ai_categorization_feedback" DROP CONSTRAINT "FK_4176f82faa6aa203d476fc20ea3"`);
        await queryRunner.query(`ALTER TABLE "group_budgets" DROP CONSTRAINT "FK_1cdfb36ba1c5b230fc8bb85774f"`);
        await queryRunner.query(`ALTER TABLE "group_comments" DROP CONSTRAINT "FK_d3672fb89d18f9947692f3294d2"`);
        await queryRunner.query(`ALTER TABLE "group_comments" DROP CONSTRAINT "FK_1bdbdc1045f1ecc53c1eaa81a9d"`);
        await queryRunner.query(`ALTER TABLE "group_comments" DROP CONSTRAINT "FK_0385d76d1946d4034a363c4234d"`);
        await queryRunner.query(`ALTER TABLE "import_logs" DROP CONSTRAINT "FK_9ab8584c123f87f734ced9aa5b6"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_fcbe490dc37a1abf68f19c5ccb9"`);
        await queryRunner.query(`ALTER TABLE "job_logs" DROP CONSTRAINT "FK_35fcfcba9d292c0c1738b8edd97"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP CONSTRAINT "FK_8d15ec28e9433be2c9c9ffbd13a"`);
        await queryRunner.query(`ALTER TABLE "reconciliations" DROP CONSTRAINT "FK_89f69f854c22241e85e23152924"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_transactions" DROP CONSTRAINT "FK_e39489108160bed58ddcdec73c6"`);
        await queryRunner.query(`ALTER TABLE "reconciliation_transactions" DROP CONSTRAINT "FK_55e3d0d29651d7e34abf0d59caf"`);
        await queryRunner.query(`ALTER TABLE "recurring_group_transactions" DROP CONSTRAINT "FK_fbf2783c89afadf2261bbdb5254"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_bed415cd29716cd707e9cb3c09c"`);
        await queryRunner.query(`ALTER TABLE "generated_reports" DROP CONSTRAINT "FK_155cad17f9ead409d635bf1d979"`);
        await queryRunner.query(`ALTER TABLE "shared_expense_transactions" DROP CONSTRAINT "FK_37970e3ecd44f15e2c46dcb7c9e"`);
        await queryRunner.query(`ALTER TABLE "shared_expense_transactions" DROP CONSTRAINT "FK_5f35ed5eab41cccf3f3914f43f6"`);
        await queryRunner.query(`ALTER TABLE "shared_expense_participants" DROP CONSTRAINT "FK_356748a64fccab022d426a99ffe"`);
        await queryRunner.query(`ALTER TABLE "shared_expense_participants" DROP CONSTRAINT "FK_e59e0fd593eb4573b4d139c32ea"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" DROP CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32"`);
        await queryRunner.query(`ALTER TABLE "user_dashboard_preferences" DROP CONSTRAINT "FK_de3bbecc57255aaa3a47d2d6029"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "email_connections" DROP CONSTRAINT "FK_7fd20b5b5314e110cf3485e6dfb"`);
        await queryRunner.query(`ALTER TABLE "reminders" DROP CONSTRAINT "FK_f8e4bc520d9e692652afaf3308b"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "lend_borrow" DROP CONSTRAINT "FK_15bc0e08b91d382c425bff2b4c6"`);
        await queryRunner.query(`ALTER TABLE "investments" DROP CONSTRAINT "FK_1ee4fc01d07959ee6cf7926fe3c"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_fdef099303bcf0ffd9a4a7b18f5"`);
        await queryRunner.query(`ALTER TABLE "group_transactions" DROP CONSTRAINT "FK_52d3ec14942246a20ec089aabe2"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_27e688ddf1ff3893b43065899f9"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_86e965e74f9cc66149cf6c90f64"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_26d8aec71ae9efbe468043cd2b9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "transaction_line_items" DROP CONSTRAINT "FK_91408ba875d13b05f5e33ab30be"`);
        await queryRunner.query(`ALTER TABLE "transaction_line_items" DROP CONSTRAINT "FK_a7a6a724f3c1992fb26f80d789d"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_92e67dc508c705dd66c94615576"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_13e8b2a21988bec6fdcbb1fa741"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51fff5114cc41723e8ca36cf22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1e9c4eea91160dfdb4318778"`);
        await queryRunner.query(`DROP TABLE "categories_closure"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccbbef396290acaece98cb129b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23ed9c8ca2e4b5cf639c580e50"`);
        await queryRunner.query(`DROP TABLE "transaction_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6364785c61032ef525bf97c2dc"`);
        await queryRunner.query(`DROP TABLE "addons"`);
        await queryRunner.query(`DROP TYPE "public"."addons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."addons_type_enum"`);
        await queryRunner.query(`DROP TABLE "ai_categorization_feedback"`);
        await queryRunner.query(`DROP TYPE "public"."ai_categorization_feedback_feedbacktype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e589da8f9e9326ee0d01a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "deleted_users"`);
        await queryRunner.query(`DROP TABLE "group_budgets"`);
        await queryRunner.query(`DROP TYPE "public"."group_budgets_period_enum"`);
        await queryRunner.query(`DROP TABLE "group_comments"`);
        await queryRunner.query(`DROP TABLE "import_logs"`);
        await queryRunner.query(`DROP TYPE "public"."import_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."import_logs_filetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3ed03c025d92c4c34131e577f"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_tier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af924c25aab35b33928211bb1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc6f555dc06b89ce79ca00685b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6975aa7cefaae1209a4784e88b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79ae682707059d5f7655db4212"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c98461a2c1599bfcf60985678d"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd7b8fde937e0dfdad9c689aa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeac166e095d6b7ecf8d154397"`);
        await queryRunner.query(`DROP TABLE "job_logs"`);
        await queryRunner.query(`DROP TYPE "public"."job_logs_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a875c91116976c6180e5ce593e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5214a8a174bf9312ae5935b6f"`);
        await queryRunner.query(`DROP TABLE "reconciliations"`);
        await queryRunner.query(`DROP TYPE "public"."reconciliations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6bc078fe62cc2ef67391e4922"`);
        await queryRunner.query(`DROP TABLE "reconciliation_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."reconciliation_transactions_matchconfidence_enum"`);
        await queryRunner.query(`DROP TABLE "recurring_group_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_group_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_group_transactions_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_group_transactions_splittype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7e731077832d2b53fa160a3e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145191ba0ef71c378ae0164b94"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4debd78ff0a7ebd62fc8913201"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38d02b1ddad80789c3721da73e"`);
        await queryRunner.query(`DROP TABLE "generated_reports"`);
        await queryRunner.query(`DROP TYPE "public"."generated_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."generated_reports_format_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa8e48aa9c9e63bc7e4a11017a"`);
        await queryRunner.query(`DROP TABLE "shared_expense_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."shared_expense_transactions_splittype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfe742520fdd67ee752446e407"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07cfc4547c2ae61a7b18e0f40a"`);
        await queryRunner.query(`DROP TABLE "shared_expense_groups"`);
        await queryRunner.query(`DROP TYPE "public"."shared_expense_groups_debtdirection_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shared_expense_groups_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c452908fa3271266e1a651389c"`);
        await queryRunner.query(`DROP TABLE "shared_expense_participants"`);
        await queryRunner.query(`DROP TYPE "public"."shared_expense_participants_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78c3bbc3ce218c9b0c62b81d51"`);
        await queryRunner.query(`DROP TABLE "usage_tracking"`);
        await queryRunner.query(`DROP TABLE "user_dashboard_preferences"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_subscriptiontier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07bd9c0d345c7e1110981e3431"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39f8752ebc359f7595484507ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57de40bc620f456c7311aa3a1e"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "email_connections"`);
        await queryRunner.query(`DROP TYPE "public"."email_connections_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_connections_provider_enum"`);
        await queryRunner.query(`DROP TABLE "reminders"`);
        await queryRunner.query(`DROP TYPE "public"."reminders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reminders_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reminders_type_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "lend_borrow"`);
        await queryRunner.query(`DROP TYPE "public"."lend_borrow_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lend_borrow_type_enum"`);
        await queryRunner.query(`DROP TABLE "investments"`);
        await queryRunner.query(`DROP TYPE "public"."investments_type_enum"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP TYPE "public"."group_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "group_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."group_transactions_splittype_enum"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_period_enum"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_reconciliationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31c0fafe7c59f688d0e7e7e322"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3dae3ed25e0d76f419fcb89ead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da2770eb9a35f7ad1fdaf64601"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e43dcec1b431001441c3983cd"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_sourcetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a6a724f3c1992fb26f80d789"`);
        await queryRunner.query(`DROP TABLE "transaction_line_items"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_type_enum"`);
    }

}
